### ISSUE TITLE
GString does not support closure with StringWriter argument under CPS

### ISSUE THREAD

**Issue by Fiouz** [cloudbees/groovy-cps#15]
The following construct does not as expected work under CPS as the closure gets a `null` argument:

```
diff --git a/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy b/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
index 9f45611..249f919 100644
--- a/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
+++ b/src/test/groovy/com/cloudbees/groovy/cps/CpsTransformerTest.groovy
@@ -367,6 +367,14 @@ class CpsTransformerTest extends AbstractGroovyCpsTest {
     }

     @Test
+    void gstringClosureStringWriter() {
+        assert evalCPS('''
+            def x = "foo";
+            return "${ w -> w << x }".toString();
+''') == "foo";
+    }
+
+    @Test
     void ternaryOp() {
         assert evalCPS('''
             return true ? 5 : null.makeCall();

```

And throws the following `NullPointerException`:

```
gstringClosureStringWriter(com.cloudbees.groovy.cps.CpsTransformerTest)  Time elapsed: 0.014 sec  <<< ERROR!
java.lang.NullPointerException: Cannot invoke method leftShift() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:77)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
        at Script1.run(Script1.groovy:3)
        at Script1.run(Script1.groovy:3)
        at ___cps.transform___(Native Method)
        at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:69)
        at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
        at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:79)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
        at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:33)
        at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
        at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:22)
        at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
        at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
        at com.cloudbees.groovy.cps.Next.step(Next.java:58)
        at com.cloudbees.groovy.cps.Next.run(Next.java:49)
        at com.cloudbees.groovy.cps.Next$run.call(Unknown Source)
        at com.cloudbees.groovy.cps.AbstractGroovyCpsTest.evalCPSonly(AbstractGroovyCpsTest.groovy:55)
        at com.cloudbees.groovy.cps.AbstractGroovyCpsTest.evalCPS(AbstractGroovyCpsTest.groovy:49)
        at com.cloudbees.groovy.cps.AbstractGroovyCpsTest$evalCPS.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
        at com.cloudbees.groovy.cps.CpsTransformerTest.gstringClosureStringWriter(CpsTransformerTest.groovy:371)
```

**Comment by Fiouz** [comment]
Submitted a unit test for that use case.
It should be noted that the current behavior is slightly different than initially reported: no more `null` argument but the result cannot be converted to a `java.lang.String` instance:
```
Assertion failed:

assert evalCPSonly(script).getClass() == java.lang.String.class
       |           |       |          |
       Foobar      |       |          false
                   |       class java.io.StringWriter

                   String text = 'Foobar';
                   String result = """${ w -> w << text}""".toString();
                   return result;
```
