### ISSUE TITLE
Closure.rehydrate() does not affect call resolution of the resulting closure

### ISSUE THREAD

**Issue by Fiouz** [cloudbees/groovy-cps#28]
The following script does not executes as expected as the `speak()` call cannot be resolved against the Script instance:

``` groovy
            class MyStrategy {
                Closure<String> process() {
                    return {
                        speak()
                    }
                }
            }
            String speak() {
                'from Script instance'
            }
            Closure<String> closure = new MyStrategy().process()
            closure.rehydrate(this, this, this).call()
```

The resolution is done against the original scope:

```
groovy.lang.MissingMethodException: No signature of method: MyStrategy.speak() is applicable for argument types: () values: []
Possible solutions: split(groovy.lang.Closure), sleep(long), sleep(long, groovy.lang.Closure), inspect(), every(), grep()
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:51)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:15)
        at MyStrategy.process(Script1.groovy:5)
        at Script1.run(Script1.groovy:13)
        at ___cps.transform___(Native Method)
        at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:48)
        at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:106)
        at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:74)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
        at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
        at com.cloudbees.groovy.cps.Next.step(Next.java:58)
        at com.cloudbees.groovy.cps.Next.run(Next.java:49)
        at com.cloudbees.groovy.cps.Next$run.call(Unknown Source)
        at com.cloudbees.groovy.cps.AbstractGroovyCpsTest.evalCPSonly(AbstractGroovyCpsTest.groovy:55)
        at com.cloudbees.groovy.cps.AbstractGroovyCpsTest.evalCPS(AbstractGroovyCpsTest.groovy:49)
        at com.cloudbees.groovy.cps.AbstractGroovyCpsTest$evalCPS.callCurrent(Unknown Source)
```

**Comment by dwnusbaum** [comment]
I am closing this issue. If it is still a problem for anyone, feel free to file an issue on https://issues.jenkins.io/ with the component set to `workflow-cps`, but note that unless you work on it yourself it is relatively unlikely that this will ever be fixed.
