### ISSUE TITLE
Resolving super to wrong class

### ISSUE THREAD

**Issue by ddmendes** [cloudbees/groovy-cps#47]
Hi, I am working on the simpletravisrunner plugin and I have something like this:

    class SimpleTravisRunner implements Serializable {
        [...]
        public void call(String path, String labelExpr = null, Integer timeout = 50, scm = null) {
            [...]
            script.node(label) {
                TravisScriptExecutorFactory executorFactory = new TravisScriptExecutorFactory()
                TravisScriptExecutor executor = executorFactory.getExecutorInstance(script, travisSteps)

                executor.loadData()
                executor.execute()
            }
        }

        private SimpleTravisRunner getSimpleTravisRunner() {
            return this
        }

        interface TravisScriptExecutor {
            public void loadData()
            public void execute()
        }

        class TravisScriptExecutorFactory implements Serializable {
            private static final def executorsMap = [
                generic: GenericTravisScriptExecutor,
                go: LanguageGoEnvironment,
            ]

            TravisScriptExecutorFactory() {}

            TravisScriptExecutor getExecutorInstance(CpsScript script, Map<String, Object> travisYml) {
                TravisScriptExecutor executor = null
                if (travisYml.containsKey("language") && executorsMap.containsKey(travisYml.get("language"))) {
                    executor = executorsMap \
                        .get(travisYml.get("language")) \
                        .newInstance(getSimpleTravisRunner(), script, travisYml)
                } else {
                    executor = executorsMap \
                        .get("generic") \
                        .newInstance(getSimpleTravisRunner(), script, travisYml)
                }

                return executor
            }
        }

        class GenericTravisScriptExecutor implements TravisScriptExecutor, Serializable {
            [...]
            GenericTravisScriptExecutor(CpsScript script, Map<String, Object> travisYml) {
                this.script = script
                this.travisYml = travisYml
            }
            [...]
            void loadData() {
                envMatrix = new TravisEnvMatrix(defaultEnv, script)

                if (travisYml.containsKey("env")) {
                    generateEnvMatrix(travisYml.get("env"), envMatrix)
                }
            }
            [...]
            void execute() {
                [...]
            }
            [...]
        }

        class LanguageGoEnvironment extends GenericTravisScriptExecutor {
            [...]
            LanguageGoEnvironment(CpsScript script, Map<String, Object> travisYml) {
                super(script, travisYml)
            }
            [...]
            @Override
            void loadData() {
                super.loadData()  // Code fails here.
                [...]
            }

            @Override
            void execute() {
                script.dir(projPath) {
                    super.loadData()
                }
            }
            [...]
        }
    }

I left in this code the relevant parts. It fails with this message:

    hudson.remoting.ProxyException: org.codehaus.groovy.runtime.InvokerInvocationException: groovy.lang.MissingMethodException: No signature of method: org.jenkinsci.plugins.simpletravisrunner.SimpleTravisRunner.loadData() is applicable for argument types: () values: []
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:97)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:830)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1128)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.superCall(DefaultInvoker.java:29)
	at org.jenkinsci.plugins.simpletravisrunner.SimpleTravisRunner$LanguageGoEnvironment.loadData(jar:file:/var/jenkins_home/plugins/simple-travis-runner/WEB-INF/lib/simple-travis-runner.jar!/org/jenkinsci/plugins/simpletravisrunner/SimpleTravisRunner.groovy:564)
	at org.jenkinsci.plugins.simpletravisrunner.SimpleTravisRunner.call(jar:file:/var/jenkins_home/plugins/simple-travis-runner/WEB-INF/lib/simple-travis-runner.jar!/org/jenkinsci/plugins/simpletravisrunner/SimpleTravisRunner.groovy:108)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:54)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:77)
	at sun.reflect.GeneratedMethodAccessor244.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:154)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:163)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:324)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:78)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:236)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:224)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:63)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
    Caused by: hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: org.jenkinsci.plugins.simpletravisrunner.SimpleTravisRunner.loadData() is applicable for argument types: () values: []
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:91)
	at org.jenkinsci.plugins.simpletravisrunner.SimpleTravisRunner.this$dist$invoke$1(SimpleTravisRunner.groovy)
	at org.jenkinsci.plugins.simpletravisrunner.SimpleTravisRunner$LanguageGoEnvironment.methodMissing(SimpleTravisRunner.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:830)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1128)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.superCall(DefaultInvoker.java:29)
	... 24 more

The thing is that the ```super.loadData()``` (from ```LanguageGoStrategy.loadData()```) is trying to call ```SimpleTravisRunner.loadData()```, the outer class, instead of ```GenericTravisScriptExecutor.loadData()```, the super class. But the super constructor call is working fine.

**Comment by dgeissl** [comment]
I'm having trouble with super calls too:
see this (shortened) base class:

```
class ComposingAction extends BuildAction{
    List<BuildAction> children = new ArrayList<BuildAction>()
    void execute(){
        for(BuildAction action : children){
            action.execute()
        }
    }
}
```

If i try to call super.execute in a class extending this one
```
class ImplAction extends ComposingAction {
    void execute(){
        super.execute()
    }
}
```
 I'll get:

```
hudson.remoting.ProxyException: com.cloudbees.groovy.cps.impl.CpsCallableInvocation
	at sun.reflect.GeneratedConstructorAccessor388.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at com.daimler.build.jenkins.actions.DoInNode.execute(DoInNode.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1160)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.superCall(DefaultInvoker.java:29)
Caused: hudson.remoting.ProxyException: org.codehaus.groovy.runtime.InvokerInvocationException: com.cloudbees.groovy.cps.impl.CpsCallableInvocation
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:100)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1160)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.superCall(DefaultInvoker.java:29)
```
Renaming the method did not work unless i also removed the super reference:
```
class ImplAction extends ComposingAction {
    void execute(){
        executeAll() // so the ComposingAction class must now have a executeAll method
    }
}
```

**Comment by jcmcken** [comment]
I'm running into this issue as well. There's also a JIRA issue for the workflow-cps-plugin for Jenkins [here](https://issues.jenkins-ci.org/browse/JENKINS-34428?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20workflow-cps-plugin%20AND%20text%20~%20%22inheritance%22).

Can we get some activity on this and other inheritance-related issues?

**Comment by radykal-com** [comment]
I'm also facing this issue. I cannot call any method from super class or from any class injected in the constructor, always getting `com.cloudbees.groovy.cps.impl.CpsCallableInvocation`

**Comment by dwnusbaum** [comment]
I am closing this, follow [JENKINS-34428](https://issues.jenkins.io/browse/JENKINS-34428) and related issues instead.
